#!/usr/bin/env bash

function atomic_append_path () {
    local regex="(^|:)""$1""(:|$)"
    if ! [[ $PATH =~ $regex ]]; then
        PATH=$PATH:$1
    fi
}

function atomic_prepend_path () {
    local regex="(^|:)""$1""(:|$)"
    if ! [[ $PATH =~ $regex ]]; then
        PATH=$1:$PATH
    fi
}

atomic_prepend_path "$HOME/.bin"
atomic_prepend_path "./bin"
atomic_prepend_path "$(brew --prefix coreutils)/libexec/gnubin"

atomic_append_path "/Applications/Postgres.app/Contents/Versions/9.4/bin"
atomic_append_path "$GOPATH/bin"
atomic_append_path "$HOME/.multirust/toolchains/nightly/cargo/bin"
atomic_append_path "$(brew --prefix git)/share/git-core/contrib/diff-highlight"
