
# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Source z
source `brew --prefix`/etc/profile.d/z.sh

# bind jj to escape
bindkey -M viins 'jj' vi-cmd-mode
